spring:
  application:
    name: service-registry

server:
  port: 8761

eureka:
  instance:
    hostname: localhost
  client:
    # This is the server ? don't register itself
    register-with-eureka: false
    fetch-registry: false
    service-url:
      defaultZone: http://localhost:8761/eureka/
  server:
    # Wait before marking instance as down
    wait-time-in-ms-when-sync-empty: 0
    enable-self-preservation: false   # disable in dev

# ?? LOGGING ???????????????????????????????????????????????????????
logging:
  level:
    com.netflix.eureka: WARN
    com.netflix.discovery: WARN

# ?? ACTUATOR ??????????????????????????????????????????????????????
management:
  endpoints:
    web:
      exposure:
        include: health,info