spring:
  datasource:
    url: jdbc:mysql://mysql-product:3306/product_db?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true
    username: nanda
    password: nanda
  kafka:
    bootstrap-servers: kafka:29092
  data:
    redis:
      host: redis        # ← THIS is the fix
      port: 6379

eureka:
  client:
    service-url:
      defaultZone: http://service-registry:8761/eureka/
  instance:
    prefer-ip-address: true